### ISSUE TITLE
Can't create new project

### ISSUE THREAD

**Issue by elimisteve** [brigadehub/core#39]
Not sure what the issue is, as the error message I receive is `[object Object]`, unfortunately.

![screenshot-codeforsf-cantcreatenewproject-screenshot_2017-11-09_01-05-41](https://user-images.githubusercontent.com/139603/32597130-91f4089c-c4ea-11e7-9997-846cf0001575.png)

**Comment by jszwedko** [comment]
Relevant logs:

```

Nov 09 17:55:54 sfbrigade app/web.1: ERROR Error: h is not a valid repo. Must contain ACCOUNT/USER. Please try again. 
Nov 09 17:55:54 sfbrigade app/web.1:     at Promise (/app/node_modules/brigadehub-admin-c4sf/controllers/projects/postProjectsNew.js:12:44) 
Nov 09 17:55:54 sfbrigade app/web.1:     at repoExistsPromise (/app/node_modules/brigadehub-admin-c4sf/controllers/projects/postProjectsNew.js:5:37) 
Nov 09 17:55:54 sfbrigade app/web.1:     at Array.map (native) 
Nov 09 17:55:54 sfbrigade app/web.1:     at postProjectsNew (/app/node_modules/brigadehub-admin-c4sf/controllers/projects/postProjectsNew.js:37:43) 
Nov 09 17:55:54 sfbrigade app/web.1:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5) 
Nov 09 17:55:54 sfbrigade app/web.1:     at next (/app/node_modules/express/lib/router/route.js:137:13) 
Nov 09 17:55:54 sfbrigade app/web.1:     at module.exports (/app/node_modules/brigadehub-core/middleware/passport/isAuthenticated.js:3:12) 
Nov 09 17:55:54 sfbrigade app/web.1:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5) 
Nov 09 17:55:54 sfbrigade app/web.1:     at next (/app/node_modules/express/lib/router/route.js:137:13) 
Nov 09 17:55:54 sfbrigade app/web.1:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3) 
Nov 09 17:55:54 sfbrigade app/web.1:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5) 
Nov 09 17:55:54 sfbrigade app/web.1:     at /app/node_modules/express/lib/router/index.js:281:22 
Nov 09 17:55:54 sfbrigade app/web.1:     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12) 
Nov 09 17:55:54 sfbrigade app/web.1:     at next (/app/node_modules/express/lib/router/index.js:275:10) 
Nov 09 17:55:54 sfbrigade app/web.1:     at sass (/app/node_modules/node-sass-middleware/middleware.js:103:14) 
Nov 09 17:55:54 sfbrigade app/web.1:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5) 
Nov 09 17:55:54 sfbrigade app/web.1:     at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13) 
Nov 09 17:55:54 sfbrigade app/web.1:     at /app/node_modules/express/lib/router/index.js:284:7 
Nov 09 17:55:54 sfbrigade app/web.1:     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12) 
Nov 09 17:55:54 sfbrigade app/web.1:     at next (/app/node_modules/express/lib/router/index.js:275:10) 
Nov 09 17:55:54 sfbrigade app/web.1:     at expressInit (/app/node_modules/express/lib/middleware/init.js:40:5) 
Nov 09 17:55:54 sfbrigade app/web.1:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5) 
Nov 09 17:55:54 sfbrigade app/web.1:     at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13) 
Nov 09 17:55:54 sfbrigade app/web.1:     at /app/node_modules/express/lib/router/index.js:284:7 
Nov 09 17:55:54 sfbrigade app/web.1:     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12) 
Nov 09 17:55:54 sfbrigade app/web.1:     at next (/app/node_modules/express/lib/router/index.js:275:10) 
Nov 09 17:55:54 sfbrigade app/web.1:     at query (/app/node_modules/express/lib/middleware/query.js:44:5) 
Nov 09 17:55:54 sfbrigade app/web.1:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5) 
```

which makes me think that maybe this issue should be moved to brigadehub/theme-admin-c4sf.

We were able to work around it by creating a project without a repository and then editing it to add the repository so this isn't urgent. I know you have taken a step back, @therebelrobot , but if you have a few free moments, they would be appreciated 😄 . We are still working on next steps for the website.

Thank you again for all of your work!

**Comment by elimisteve** [comment]
> We were able to work around it by creating a project without a repository and then editing it to add the repository

This indeed worked for me, thanks!
